export const FILES_LIST_REQUEST = 'FILES_LIST_REQUEST';
export const FILES_LIST_SUCCESS = 'FILES_LIST_SUCCESS';
export const FILES_LIST_FAIL = 'FILES_LIST_FAIL';

export const FILES_CREATE_REQUEST = 'FILES_CREATE_REQUEST';
export const FILES_CREATE_SUCCESS = 'FILES_CREATE_SUCCESS';
export const FILES_CREATE_FAIL = 'FILES_CREATE_FAIL';

export const FILES_SHARED_LIST_REQUEST = 'FILES_SHARED_LIST_REQUEST';
export const FILES_SHARED_LIST_SUCCESS = 'FILES_SHARED_LIST_SUCCESS';
export const FILES_SHARED_LIST_FAIL = 'FILES_SHARED_LIST_FAIL';

export const FILES_DOWNLOAD_REQUEST = 'FILES_DOWNLOAD_REQUEST';
export const FILES_DOWNLOAD_SUCCESS = 'FILES_DOWNLOAD_SUCCESS';
export const FILES_DOWNLOAD_FAIL = 'FILES_DOWNLOAD_FAIL';

export const FILES_SHARE_REQUEST = 'FILES_SHARE_REQUEST';
export const FILES_SHARE_SUCCESS = 'FILES_SHARE_SUCCESS';
export const FILES_SHARE_FAIL = 'FILES_SHARE_FAIL';

export const FILES_RENAME_REQUEST = 'FILES_RENAME_REQUEST';
export const FILES_RENAME_SUCCESS = 'FILES_RENAME_SUCCESS';
export const FILES_RENAME_FAIL = 'FILES_RENAME_FAIL';

export const FILES_DELETE_REQUEST = 'FILES_DELETE_REQUEST';
export const FILES_DELETE_SUCCESS = 'FILES_DELETE_SUCCESS';
export const FILES_DELETE_FAIL = 'FILES_DELETE_FAIL';
